=== clarin-eric/clarin-resource-families/schemas/spec-corpora-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/clarin-eric/clarin-resource-families/refs/heads/main/schemas/spec-v1.schema.json",
  "title": "JSON Schema for the CLARIN Resource Families",
  "type": "object",
  "definitions": {},
  "required": [
    "Name",
    "URL",
    "Family",
    "Description",
    "Language",
    "Licence",
    "Size",
    "Annotation",
    "Infrastructure",
    "Access",
    "Publication"
  ],
  "properties": {
    "Access": {
      "$id": "#/properties/Access",
      "type": "object",
      "title": "Access information for the resource",
      "minProperties": 1
    },
 "Family": {
  "$id": "#/properties/Family",
  "anyOf": [
    {
      "type": "string",
      "enum": [
        "Academic corpora",
        "Computer-mediated communication corpora",
        "Corpora of Disordered Speech",
        "Historical corpora",
        "L2 learner corpora",
        "Legal corpora",
        "Literary corpora",
        "Manually annotated corpora",
	"Multimodal corpora",
        "Newspaper corpora",
        "Oral History corpora",
        "Parallel corpora",
        "Parliamentary corpora",
        "Reference corpora",
        "Sign language resources",
        "Spoken corpora",
        "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"        
      ]
    },
    {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Academic corpora",
          "Computer-mediated communication corpora",
          "Corpora of Disordered Speech",
          "Historical corpora",
          "L2 learner corpora",
          "Legal corpora",
          "Literary corpora",
          "Manually annotated corpora",
          "Newspaper corpora",
          "Oral History corpora",
          "Parallel corpora",
          "Parliamentary corpora",
          "Reference corpora",
          "Sign language resources",
          "Spoken corpora",
          "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"
        ]
      },
      "uniqueItems": true
    }
  ]
},

      "Description": {
      "$id": "#/properties/Description",
      "type": "string",
      "title": "Resource's description"
    },
    "Name": {
      "$id": "#/properties/Name",
      "title": "Resource name",
      "type": "string"
    },
    "URL": {
      "$id": "#/properties/URL",
      "type": "string",
      "format": "uri",
      "pattern": "^https?://",
      "title": "Link to the resource (PID preferred)",
      "examples": ["https://example.com"]
    },
    "Language": {
      "$id": "#/properties/Language",
      "type": "array",
      "title": "Languages that the tool can work with",
      "items": {
        "$id": "#/properties/languages/items",
        "type": "string",
        "title": "Language Identifier, ISO 693-3",
        "default": "eng",
        "examples": ["eng", "deu"],
        "pattern": "^(.{3})|(generic)$"
      }
     },
    "Licence": {
      "$id": "#/properties/Licence",
      "type": ["array", "string", "null"],
      "title": "Resource's licence",
      "default": null
    },
    "Size": {
      "$id": "#/properties/Size",
      "type": ["array", "string", "null"],
      "title": "Size of the resource, multiple formats possible",
      "default": null
    },
    "Annotation": {
      "$id": "#/properties/Annotation",
      "type": ["array", "string", "null"],
      "title": "Annotation layers in this resource",
      "default": null
    },
      "Infrastructure": {
      "$id": "#/properties/Infrastructure",
      "type": "string",
      "title": "which infrastructure does this item belong to"
    },
    "Publication": {
      "$id": "#/properties/Publication",
     "anyOf": [
        {
     "type": "array",
      "items": {
        "type": "string",
        "pattern": "^https?://|^$"
      },
    "uniqueItems": true
      },
{      "type": "string",
      "pattern": "^https?://|^$"
      }
      ],
      "title": "Link to a publication about the resource (PID preferred)",
      "examples": ["https://example.com"]
    }
 }
 }

=== clarin-eric/clarin-resource-families/corpora/parliamentary-corpora/europarl.json
{
      "Name": "Europarl: European Parliament Proceedings Parallel Corpus 1996-2011",
      "URL": "https://www.statmt.org/europarl/",
	"Family": "Parliamentary corpora",
      "Description": "This corpus contains parliamentary debates from the European Parliament from 1996 to 2011.\nThe corpus is available for download from a dedicated webpage.",
      "Language": ["bul", "ces", "dan", "deu", "ell", "eng", "spa", "est", "fin", "hun", "ita", "lit", "lav", "nld", "pol", "por", "ron", "slk", "slv", "swe"],
      "Licence": "CC0",
      "Size": ["33.7 million tokens"],
      "Annotation": ["sentence/aligned"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "http://www.statmt.org/europarl/"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/literary-corpora/nornyn-children.json
{
      "Name": "NorGrambank children's fiction in Norwegian Nynorsk",
      "URL": "http://hdl.handle.net/11495/D963-33EA-65BD-0",
	"Family": "Literary corpora",
      "Description": "This corpus, which is based on OCR data from the National Library of Norway, is available for online browsing through INESS.",
      "Language": ["nno"],
      "Licence": "CLARIN ACA",
      "Size": ["1,043,260 words", "106,434 sentences"],
      "Annotation": ["syntactically parsed"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Browse": "http://clarino.uib.no/iness/landing-page?collection=NorGramBank"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/spoken-corpora/griffith-australian.json
{
      "Name": "Griffith Corpus of Spoken Australian English",
      "URL": "https://doi.org/10.21415/T53W33",
	"Family": "Spoken corpora",
      "Description": "This corpus comprises a collection of forty audio recordings and transcriptions of spoken interaction amongst Australian speakers of English, as well as users of English in Australia more generally, collected by staff and students at Griffith University. The recordings are transcribed using conversation analysis transcription conventions.\nThis corpus is available for download from TalkBank.",
      "Language": ["eng"],
      "Licence": "",
      "Size": ["32,134 words"],
      "Annotation": [],
      "Infrastructure": "Other",
      "Access": {
	"Download": "https://doi.org/10.21415/T53W33"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/couranten-corpus.json
{
      "Name": "Couranten Corpus ",
      "URL": "http://hdl.handle.net/10032/tm-a2-u9",
	"Family": "Historical corpora",
      "Description": "This is a corpus of 17th-century Dutch newspapers.\nThe corpus is available from the Dutch Language Institute.",
      "Language": ["nld"],
      "Licence": "",
      "Size": [""],
      "Annotation": ["", ""],
      "Infrastructure": "CLARIN",
      "Access": {
	"Browse": "https://couranten.ivdnt.org/corpus-frontend/couranten/search/"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/parliamentary-corpora/bundestag-europe.json
{
      "Name": "Parliamentary Debates on Europe at the Bundestag (1998-2015)",
      "URL": "https://hdl.handle.net/11403/de-parl/v1",
	"Family": "Parliamentary corpora",
      "Description": "The corpus contains German parliamentary debates from 1998 to 2015. The contextual metadata in the corpus concern the dates of the council meetings, the description of the main topic(s) of the European council meeting, the place where the European Council meeting took place; they also correspond to information about the government and the legislative session. The speaker metadata correspond to name, gender, occupation, parliamentary group, political orientation and the opposition and majority division.\nThe corpus is available for download from Ortolang.",
      "Language": ["deu"],
      "Licence": "CC-BY",
      "Size": ["417,000 tokens"],
      "Annotation": ["contextual and speaker metadata"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "https://hdl.handle.net/11403/de-parl/v1"
	},
      "Publication": "Truan and Romary (2021)"
}

=== clarin-eric/clarin-resource-families/corpora/cmc-corpora/ancillary-monitor-corpus.json
{
      "Name": "Ancillary Monitor Corpus: Common Crawl - German Web",
      "URL": "http://hdl.handle.net/11372/LRT-5811",
	"Family": "Computer-mediated communication corpora",
      "Description": "This is a continuously updated corpus of the German-language internet, with a new release published every year.\nThe corpus currently covers the years 2013-2024.\nThe corpus is based on data dumps from <a href=\"https://commoncrawl.org/\">CommonCrawl</a>.\n The filtering and subsequent processing was carried out using <a href=\"http://hdl.handle.net/11234/1-2634\">CorpusExplorer</a> with additional supplementary scripts, and <a href=\"http://hdl.handle.net/11372/LRT-323\">TreeTagger</a> was used for the automatic annotation.\nThe corpus is available for download from LINDAT.",
      "Language": ["deu"],
      "Licence": "CC BY-NC-SA 4.0",
      "Size": ["12,743,367 texts", "14,360,469,888 tokens"],
      "Annotation": ["tokenised", "sentence tagging", "PoS-tagged", "lemmatised"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "http://hdl.handle.net/11372/LRT-5811"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/literary-corpora/1000plus-novels.json
{
      "Name": "1000PLUS Novels Corpus (1.0)",
      "URL": "http://hdl.handle.net/11321/699",
	"Family": "Literary corpora",
      "Description": "This corpus is available for download from CLARIN-PL.",
      "Language": ["pol"],
      "Licence": "CC BY-SA 3.0",
      "Size": ["1000 texts", "17,352,826 words"],
      "Annotation": [],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "http://hdl.handle.net/11321/699"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/literary-corpora/strindberg.json
{
      "Name": "August Strindberg's novels (2017-10-16)",
      "URL": "http://hdl.handle.net/10794/79",
	"Family": "Literary corpora",
      "Description": "This corpus presents the collected works of August Strindberg.\nThe corpus is available for download from SWE-CLARIN and for online browsing through Korp.",
      "Language": ["swe"],
      "Licence": "CC BY 4.0",
      "Size": ["4,309,037 tokens", "321,759 sentences"],
      "Annotation": ["sentence scrambling"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Browse": "https://spraakbanken.gu.se/korp/#?corpus=strindbergromaner",
	"Download": "http://hdl.handle.net/10794/79"
	},
      "Publication": ""
}
